AllCops:
  Exclude:
    - test/dummy/db/schema.rb
    - test/dummy/db/migrate/*
    - iconly.gemspec
    - bin/*

Metrics/LineLength:
  Max: 125

Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 25
