{
  "checksum": {
    "current": "",
    "previous": ""
  },
  "fonts": [
    "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/fonts/iconly.ttf",
    "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/fonts/iconly.svg",
    "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/fonts/iconly.woff",
    "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/fonts/iconly.eot"
  ],
  "glyphs": {
    "facebook": {
      "codepoint": 61751,
      "source": "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-rmc1wq/facebook.svg"
    },
    "twitter": {
      "codepoint": 61752,
      "source": "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-rmc1wq/twitter.svg"
    }
  },
  "options": {
    "autowidth": false,
    "config": false,
    "css_selector": ".iconly-{{glyph}}",
    "debug": false,
    "font_ascent": 448,
    "font_descent": 64,
    "font_design_size": 16,
    "font_em": 512,
    "font_name": "iconly",
    "force": false,
    "input": {
      "templates": "/Users/arti/work/lugo/iconly/iconly/config/fontcustom/templates",
      "vectors": "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-rmc1wq"
    },
    "no_hash": true,
    "output": {
      "css": "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz",
      "fonts": "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/fonts",
      "preview": "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/fonts"
    },
    "preprocessor_path": null,
    "quiet": false,
    "templates": [
      "iconly.css"
    ],
    "verbose": true
  },
  "templates": [
    "/var/folders/py/mnqh0bdx1w13jgvmw_ls9tjr0000gn/T/d20170204-7208-a5r5oz/iconly.css"
  ]
}